### ISSUE TITLE
dexnet.api:Failed to import DexNetVisualizer3D

### ISSUE THREAD

**Issue by LJN96** [BerkeleyAutomation/dex-net#20]
This error is produced every time the cli is launched.

`WARNING:dexnet.api:Failed to import DexNetVisualizer3D, visualization methods will be unavailable`

After numerous installs and investigations there do not appear to be any dependency issues. The kinect/libfreenect packages are not yet installed but I do not think that would be causing this. 

Could there be some bad file-paths in the source code? Has this issue been encountered before?

**Comment by LJN96** [comment]
Solved by changing line 50 in dex-net/api.py

from:

`try:
    from dexnet.visualization import DexNetVisualizer3D as vis
except:
logger.warning('Failed to import DexNetVisualizer3D, visualization methods will be unavailable')`

to:

`from dexnet.visualization.visualizer3d import DexNetVisualizer3D as vis`

**Comment by kundan09** [comment]
@jeffmahler can u please help me .
i have installed dexnet and geeting error as :- :Failed to import DexNetVisualizer3D

:Unable to import pylibfreenect2. Python-only Kinect driver may not work properly.
WARNING:root:primesense_sensor.py not installed as catkin package. ROS functionality not available.
WARNING:root:Failed to import ROS in phoxi_sensor.py. PhoXiSensor functionality unavailable.
WARNING:dexnet.api:Failed to import DexNetVisualizer3D, visualization methods will be unavailable
test_illegal_create (__main__.Hdf5DatabaseTest) ... ok
test_new_database_and_graspable (__main__.Hdf5DatabaseTest) ... Input mesh  /home/robo/catkin_ws/src/dex-net/data/test/models/bar_clamp.obj
output mesh  /home/robo/catkin_ws/src/dex-net/.dexnet/bar_clamp_proc.obj
Loading Plugins:
Current Plugins Dir is: /usr/lib/meshlab/plugins 
Error in XMLFile: filter_measure.xml - line: -1, column: -1 - 
Error in XMLFile: filter_mutualinfo.xml - line: -1, column: -1 - 
Total 227 filtering actions
Total 13 io plugins
Opening a file with extention obj
Mesh bar_clamp.obj loaded has 1428 vn 476 fn
No Script to apply.
Mesh /home/robo/catkin_ws/src/dex-net/data/test/models/bar_clamp.obj saved as /home/robo/catkin_ws/src/dex-net/.dexnet/bar_clamp_proc.obj (1428 vn 476 fn)
INFO:root:MeshlabServer Command: meshlabserver -i "data/test/models/bar_clamp.obj" -o ".dexnet/bar_clamp_proc.obj"
Reading data.
Warning: 9 lines were ignored since they did not contain faces or vertices.
Read in 1428 vertices and 476 faces.
Resolution: 0.000716689 with real dimension 0.064502
Center of grid 0 0 0
Bound box size: (-0.0358344 -0.0358344 -0.0358344) to (0.021729 0.02 0.032251) with dimensions 100 100 100.
Computing signed distance field.
Writing results to: .dexnet/bar_clamp_proc.sdf
Processing complete.
INFO:root:SDF Command: SDFGen ".dexnet/bar_clamp_proc.obj" 100 5
INFO:root:Returning datum bar_clamp
WARNING:root:No rendered images of type segmask for stable pose pose_0
WARNING:root:No rendered images of type depth for stable pose pose_0
WARNING:root:No rendered images of type scaled_depth for stable pose pose_0
ok
