### ISSUE TITLE
a problem about the grasp generation.

### ISSUE THREAD

**Issue by pyni** [BerkeleyAutomation/dex-net#27]
I use the costum-dataset branch to generate the grasp.
However, after sampling grasps and calculating the metrics, the center of the grasps is very large (almost nearly [50,50,50]). While the center of the object is amostly [0,0,0]. 
Later, i find out that it is the sampling method that samples from a strange SDF.
I use the following code:
            vasedata=self.dexnet_api.database.dataset('mini_dexnet')['vase']
            vasedata.sdf.surface_points(grid_basis=False)

And it shows:
![image](https://user-images.githubusercontent.com/18031767/50833229-7ffa4200-138b-11e9-8813-a2fc789f0bed.png)
 This is strange. I can hardly understand why SDF is so large, and how can my problem be solved.

**Comment by SilviaSapora** [comment]
I found the cause of this is. I think there is an inconsistency between the way the SDF is generated(by SDFGen) and the library that is creating the SDF3D python object(Meshpy). The problem can be solved by changing the Sdf3D file in Meshpy. If you go read the init function of Sdf3D, you'll find that at one point one of the transformation matrices is divided by the resolution. If you remove that division the SDF creation will work as expected.
I'm sorry I didn't answer this earlier but the issue was closed so I didn't notice.

**Comment by pyni** [comment]
Yes, it works. That is the point.
Thanks again!

**Comment by wjydou** [comment]
hey,how do you do with your own data to create the training set?

**Comment by wjydou** [comment]
@pyni
