### ISSUE TITLE
Issue with displaying objects

### ISSUE THREAD

**Issue by vribic** [BerkeleyAutomation/dex-net#9]
When trying to display an object either from dexnet_cli or through API the following error occurs:

Display grasps failed: Must provide a trimesh.Trimesh object

Do you have any solutions?

**Comment by vribic** [comment]
Ok, I solved my problems by changing:

`vis.mesh(obj.mesh, color=(0.5,0.5,0.5), style='surface) `

to

`vis.mesh(obj.mesh.trimesh, color=(0.5,0.5,0.5), style='surface) `.

Still, I'm not sure if this is the complete solution and if there is a need to change this in other parts of API.

**Comment by jeffmahler** [comment]
Your solution is correct, however it appears that there are many other functions that are likely broken due to a recent update to the visualization module.

Thank you very much for raising this issue. We will push a fix to the dex-net master branch as soon as possible.

**Comment by jeffmahler** [comment]
Ok this problem should be resolved with the latest commit.
Please run:
`git pull origin master`
from the dex-net repo to get the updates.

We are migrating dex-net to use the [trimesh](https://github.com/mikedh/trimesh/tree/master/trimesh) library because of several improvements to meshpy and better community support for trimesh. We will release a new version of dex-net later this spring to reflect this.
